// Generated by uniffi-bindgen-react-native
package com.myrustlib;

import androidx.annotation.NonNull;

import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.module.annotations.ReactModule;
import com.facebook.react.turbomodule.core.interfaces.CallInvokerHolder;

@ReactModule(name = MyRustLibModule.NAME)
public class MyRustLibModule extends NativeMyRustLibSpec {
  public static final String NAME = "MyRustLib";

  public MyRustLibModule(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  @NonNull
  public String getName() {
    return NAME;
  }

  static {
    System.loadLibrary("my-rust-lib");
  }

  private static native boolean nativeInstallRustCrate(long rtPtr, CallInvokerHolder callInvoker);
  private static native boolean nativeCleanupRustCrate(long rtPtr);

  @Override
  public boolean installRustCrate() {
    ReactApplicationContext context = getReactApplicationContext();
    return nativeInstallRustCrate(
      context.getJavaScriptContextHolder().get(),
      context.getCatalystInstance().getJSCallInvokerHolder()
    );
  }

  @Override
  public boolean cleanupRustCrate() {
    return nativeCleanupRustCrate(
      this.getReactApplicationContext().getJavaScriptContextHolder().get()
    );
  }
}