// Generated by uniffi-bindgen-react-native
import installer from './NativeMyRustLib';

// Register the rust crate with Hermes
installer.installRustCrate();

// Export the generated bindings to the app.
export * from './generated/foobar';

// Initialize the generated bindings: mostly checksums, but also callbacks.
import foobar_ from './generated/foobar';

foobar_.initialize();
